tests for question and answer
dan-abramov/thinknetica-advanced pull request #1
Opened 2017-05-21 12:29 UTC by dan-abramov

added gem rubocop

merged all commit changes

2017-05-21 21:31 UTC, webmstk requested changes

2017-05-21 21:31 UTC, webmstk commented on db/migrate/20170520224005_add_foreign_key_to_answer.rb
> +    add_column :answers, :question_id, :integer
надо добавить внешний ключ на эту колонку, посмотри http://rusrails.ru/rails-database-migrations#foreign-keys

2017-05-21 21:31 UTC, webmstk commented on spec/models/answer_spec.rb
> +  it {should belong_to (:question)}
в тестах тоже лучше сначала связи, потом валидации тестировать

2017-05-21 21:31 UTC, webmstk commented on spec/factories/answers.rb
> +    body "MyText"
добавь связь с фабрикой вопроса, чтобы ответ создавался уже с вопросом http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Associations

2017-05-22 11:20 UTC, webmstk commented on db/migrate/20170520224005_add_foreign_key_to_answer.rb
> +    add_column :answers, :question_id, :integer
делается так
```
def change
  add_reference :answers, question, foreign_key: true
end
```
ещё у `add_reference` есть алиас `add_belongs_to`, не удивляйся, если встретишь

именно такую миграцию сгенерит команда
```
rails g migration add_question_id_to_answers question:references
# или
rails g migration add_question_id_to_answers question:belongs_to
```

2017-05-22 11:20 UTC, webmstk commented on db/migrate/20170522105208_add_foreign_key_to_answer.rb
> +    add_foreign_key :answers, :questions
делается так
```
def change
  add_reference :answers, question, foreign_key: true
end
```
ещё у `add_reference` есть алиас `add_belongs_to`, не удивляйся, если встретишь

именно такую миграцию сгенерит команда
```
rails g migration add_question_id_to_answers question:references
# или
rails g migration add_question_id_to_answers question:belongs_to
```

2017-05-22 12:47 UTC, palkan-th requested changes

2017-05-22 12:47 UTC, palkan-th commented on spec/rails_helper.rb
> +    require 'active_record'
Это зачем?

2017-05-22 12:47 UTC, palkan-th commented on spec/models/question_spec.rb
> +  it {should validate_presence_of :title }
С форматированием надо что-то придумать: в начале блоке у тебя нет пробела, в конце есть (предпочтительней вариант, когда пробелы есть с обеих сторон). Код должен быть аккуратным.

2017-05-22 12:47 UTC, palkan-th commented on spec/factories/answers.rb
> +    body "MyText"
Да, фабрику надо поправить.

2017-05-22 13:12 UTC, dan-abramov commented on spec/rails_helper.rb
> +    require 'active_record'
Как ни странно, но без этого мне выдавалась ошибка. И без `require 'action_controller'` тоже.

2017-05-22 13:14 UTC, dan-abramov commented on spec/models/question_spec.rb
> +  it {should validate_presence_of :title }
Спасибо, поправлю.

2017-05-22 14:12 UTC, dan-abramov commented on spec/factories/answers.rb
> +    question
Добавил.

2017-05-23 06:42 UTC, webmstk commented on db/migrate/20170522105208_add_foreign_key_to_answer.rb
> +    add_column :answers, :question_id, :integer
добавь ещё индекс на колонку `question_id`
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_index

Кстати, `add_reference` сделал бы это автоматом ;)

2017-05-23 15:13 UTC, merged