Ajax part 1
dan-abramov/thinknetica-advanced pull request #5
Opened 2017-06-08 19:39 UTC by dan-abramov

2017-06-09 20:57 UTC, palkan-th requested changes

2017-06-09 20:57 UTC, palkan-th commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render "answers" %>');
Внимательно читаем текст задания: нужно добавлять только вновь созданный ответ к вопросу, без повторного рендеринга всего списка.

А здесь получается как раз рендеринг всего списка.

2017-06-11 11:50 UTC, palkan-th requested changes

2017-06-11 11:50 UTC, palkan-th commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
А ты пробовал это вариант, когда у тебя уже есть ответы на вопрос? Такой код сотрёт все ответы и отобразит только новый.

Посмотри на функцию `append` в jQuery.

2017-06-11 14:02 UTC, dan-abramov commented on app/views/answers/create.js.erb
> +$('.answers').html('<%= j render @answer %>');
Да, конечно, я пробовал)
Мне это показалось странным, но подумал, что вдруг это нормально и такой опыт уже где-то применяется) 
Оказалось, что я неправильно понял опять задание...

2017-06-11 14:02 UTC, dan-abramov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Это я хотел посмотреть будет работать этот вариант или нет. Работает)

2017-06-11 14:02 UTC, dan-abramov commented on app/views/answers/create.js.erb
> +$('.answers').children('.no-answers').empty()
Так как у меня на странице show есть логика написать (Here is no answers) если нету ответов, то теперь jQuery будет удалять эту строку при первом появившемся комментарии и последующих тоже.

2017-06-11 19:34 UTC, palkan-th commented on app/views/answers/create.js.erb
> +$('.answers').children('.no-answers').empty()
Ага, отлично. Но можно, наверное, проще? `$('.no-answers').remove()`

2017-06-11 20:21 UTC, dan-abramov commented on app/views/answers/create.js.erb
> +$('.answers').children('.no-answers').empty()
Так точно! Я просто хотел конкретизировать, чтобы если где-нибудь еще создам класс  no-comments, он бы не стирался. Поэтому в начале написал: `$('.answers').children...`
А remove, действительно логичнее использовать.

2017-06-11 20:22 UTC, merged